# Generated by Django 4.1.2 on 2022-12-20 09:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profisle_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profisle',
            new_name='Profile',
        ),
    ]
