# Generated by Django 4.1.4 on 2022-12-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUsers',
        ),
    ]
