# Generated by Django 4.1.2 on 2022-11-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=30)),
                ('clientSurname', models.CharField(max_length=30)),
                ('ClientImage', models.ImageField(upload_to='images/clientimages')),
            ],
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=30)),
                ('serviceImage', models.ImageField(upload_to='images/serviceimages')),
            ],
        ),
        migrations.CreateModel(
            name='PetGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=50)),
                ('petimage', models.ImageField(upload_to='images/petimages')),
            ],
        ),
    ]
