# Generated by Django 4.1.2 on 2022-11-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_client_clientcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petgallery',
            name='petName',
        ),
    ]
