# Generated by Django 4.1.2 on 2022-12-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_petgallery_petname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=30)),
                ('Breed', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=2)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/petimages')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='ClientImage',
            field=models.ImageField(null=True, upload_to='images/clientimages'),
        ),
    ]
