# Generated by Django 4.1.4 on 2022-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_pets_alter_client_clientimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='serviceDetails',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='serviceIcon',
            field=models.ImageField(null=True, upload_to='images/serviceimages'),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='serviceImage',
            field=models.ImageField(null=True, upload_to='images/serviceimages'),
        ),
    ]
