# Generated by Django 4.1.4 on 2022-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='serviceSubHead',
            field=models.TextField(null=True),
        ),
    ]
