# Generated by Django 4.1.2 on 2023-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slide')),
                ('title', models.CharField(max_length=30)),
                ('subTitle', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=80)),
            ],
        ),
    ]
